/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import javax.swing.JOptionPane;

/**
 *
 * @author shakthi
 */
public class LoadingPage extends javax.swing.JFrame {

    /**
     * Creates new form LoadingPage
     */
    public LoadingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        progressBarCustom2 = new com.component.ProgressBarCustom();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 149, 0), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Loading.......");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 410, -1, -1));

        progressBarCustom2.setBackground(new java.awt.Color(255, 255, 255));
        progressBarCustom2.setForeground(new java.awt.Color(255, 149, 0));
        progressBarCustom2.setValue(20);
        progressBarCustom2.setColor1(new java.awt.Color(255, 149, 0));
        jPanel1.add(progressBarCustom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 430, 800, 6));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/loading_image.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 149, 0), 1, true));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        FlatIntelliJLaf.setup();

        LoadingPage lp = new LoadingPage();
        SignIn s = new SignIn();

        lp.setVisible(true);

        try {

            for (int i = 0; i <= 100; i++) {
                Thread.sleep(60);
//                lp.jLabel2.setText(i + "%");

                if (i == 10) {
                    lp.jLabel2.setText("Turning On Modules....");
                } else if (i == 20) {
                    lp.jLabel2.setText("Loding Modules....");
                } else if (i == 50) {
                    lp.jLabel2.setText("Connecting To Database....");
                } else if (i == 70) {
                    lp.jLabel2.setText("Connecting To Successful....");
                } else if (i == 80) {
                    lp.jLabel2.setText("Launching Application....");
                }

                lp.progressBarCustom2.setValue(i);
            }

            lp.dispose();
            s.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private com.component.ProgressBarCustom progressBarCustom2;
    // End of variables declaration//GEN-END:variables
}
