/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.model.MySQL;
import java.sql.ResultSet;
import java.awt.Image;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import raven.toast.Notifications;

/**
 *
 * @author shakthi
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * @return the employeeEmail
     */
    public static String getEmployeeEmail() {
        return employeeEmail;
    }

    /**
     * @param aEmployeeEmail the employeeEmail to set
     */
    public static void setEmployeeEmail(String aEmployeeEmail) {
        employeeEmail = aEmployeeEmail;
    }
    
    private static String employeeEmail;

    /**
     * Creates new form Home
     */
    public SignIn() {
        initComponents();
        
        Image icon = new ImageIcon(this.getClass().getResource("/com/res/logo1.png")).getImage();
        this.setIconImage(icon);
        
         Notifications.getInstance().setJFrame(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonGradent2 = new com.component.ButtonGradent();
        buttonGradent3 = new com.component.ButtonGradent();
        jLabel2 = new javax.swing.JLabel();
        buttonGradent4 = new com.component.ButtonGradent();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textField2 = new com.component.TextField();
        passwordTextField2 = new com.component.PasswordTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 149, 0), 2, true));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/sidnin_image.png"))); // NOI18N

        buttonGradent2.setColor1(new java.awt.Color(255, 184, 0));
        buttonGradent2.setColor2(new java.awt.Color(255, 184, 0));
        buttonGradent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradent2ActionPerformed(evt);
            }
        });

        buttonGradent3.setColor1(new java.awt.Color(255, 59, 48));
        buttonGradent3.setColor2(new java.awt.Color(255, 59, 48));
        buttonGradent3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradent3ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/Logo.png"))); // NOI18N

        buttonGradent4.setText("Sign In");
        buttonGradent4.setColor1(new java.awt.Color(255, 149, 0));
        buttonGradent4.setColor2(new java.awt.Color(255, 59, 48));
        buttonGradent4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonGradent4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradent4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("SIGN IN");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Username");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Password");

        jLabel6.setForeground(new java.awt.Color(255, 59, 48));
        jLabel6.setText("Enter your correct username and password.....");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/res/icons8-light-on-18.png"))); // NOI18N

        textField2.setBackground(new java.awt.Color(246, 246, 246));
        textField2.setHintText("Enter Your Username or Email");
        textField2.setShowicon(true);

        passwordTextField2.setBackground(new java.awt.Color(246, 246, 246));
        passwordTextField2.setAnimationColor(new java.awt.Color(255, 153, 51));
        passwordTextField2.setSelectionColor(new java.awt.Color(255, 153, 0));
        passwordTextField2.setShowAndHide(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(buttonGradent3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(buttonGradent2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(9, 9, 9)))
                            .addGap(158, 158, 158))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addGap(116, 116, 116))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(332, 332, 332))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(passwordTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonGradent4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonGradent3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGradent2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonGradent4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGradent3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradent3ActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_buttonGradent3ActionPerformed

    private void buttonGradent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradent2ActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(this.ICONIFIED);
    }//GEN-LAST:event_buttonGradent2ActionPerformed

    private void buttonGradent4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradent4ActionPerformed
        // TODO add your handling code here:
        String UserName = textField2.getText();
        String Password = String.valueOf(passwordTextField2.getPassword());
        
        if(UserName.isEmpty()){
            Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_RIGHT, "Plese enter your UserName or Email");
        }else if(!Pattern.matches("^(?=.{1,64}@)[A-Za-z0-9\\+_-]+(\\.[A-Za-z0-9\\+_-]+)*@"
                + "[^-][A-Za-z0-9\\+-]+(\\.[A-Za-z0-9\\+-]+)*(\\.[A-Za-z]{2,})$", UserName)){
            Notifications.getInstance().show(Notifications.Type.WARNING,Notifications.Location.TOP_RIGHT,"Plese valid your UserName or Email");
        }else if(Password.isEmpty()){
            Notifications.getInstance().show(Notifications.Type.WARNING,Notifications.Location.TOP_RIGHT,"Plese enter your Password");
        }else{
        
        try {
            
            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `employee` WHERE `email`='"+UserName+"' AND `password`='"+Password+"'");
            
            if(resultSet.next()){
                String ad_id = resultSet.getString("ad_id");
                String fname = resultSet.getString("fname");
                String lname = resultSet.getString("lname");
                String contact = resultSet.getString("contact_no");
                
//                System.out.println(fname);
//                System.out.println(lname);

               Home home = new Home(ad_id,fname,lname,contact);
               home.setVisible(true);
               this.dispose();
               
                setEmployeeEmail(UserName);
            }else{
                Notifications.getInstance().show(Notifications.Type.ERROR,Notifications.Location.TOP_RIGHT,"Plese Check your Email and Password");
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_buttonGradent4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        FlatMacLightLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.component.ButtonGradent buttonGradent2;
    private com.component.ButtonGradent buttonGradent3;
    private com.component.ButtonGradent buttonGradent4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private com.component.PasswordTextField passwordTextField2;
    private com.component.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
